version: "3.7"

services:
  dts:
    image: depscloud/dts:latest
    hostname: dts

  des:
    image: depscloud/des:latest
    hostname: des
    
  dis:
    image: depscloud/dis:latest
    hostname: dis
    depends_on:
    - des
    - dts
    volumes:
    - ./rds.yaml:/etc/rds/config.yaml
    command:
    - --cron
    - --rds-config=/etc/rds/config.yaml
    - --workers=1

  gateway:
    image: depscloud/gateway:latest
    hostname: gateway
    depends_on:
    - des
    - dts
    ports:
    - 8080:8080
