apiVersion: v1
kind: ConfigMap
metadata:
  namespace: depscloud-system
  name: rds-config
  labels:
    app: depscloud
data:
  config.yaml: |
    accounts:
    - github:
        strategy: HTTP
        organizations:
        - deps-cloud

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: depscloud-system
  name: dis
  labels:
    app: depscloud
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: config
            configMap:
              name: rds-config
          initContainers:
          - name: service-precheck
            image: mjpitz/service-precheck:latest
            imagePullPolicy: IfNotPresent
            args:
            - "rds"
            - "des"
            - "dts"
          containers:
          - name: dis
            image: depscloud/dis:latest
            imagePullPolicy: IfNotPresent
            args:
            - "--cron"
            - "--rds-config=/etc/rds/config.yaml"
            volumeMounts:
            - name: config
              mountPath: /etc/rds
              readOnly: true
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
          restartPolicy: OnFailure
