version: "3.7"

services:
  dts:
    image: depscloud/dts:latest
    hostname: dts

  rds:
    image: depscloud/rds:latest
    hostname: rds
    volumes:
    - ./rds.ssh.yaml:/etc/rds/config.yaml
    command:
    - --config=/etc/rds/config.yaml

  des:
    image: depscloud/des:latest
    hostname: des
    
  ## generate an ssh key to use: `ssh-keygen -b 2048 -t rsa -f test`
  ## upload to github / hosting service
  dis:
    image: depscloud/dis:latest
    hostname: dis
    volumes:
    - ./known_hosts:/home/dis/.ssh/known_hosts
    - ./test:/home/dis/.ssh/id_rsa
    command:
    - --ssh-keypath=/home/dis/.ssh/id_rsa
    depends_on:
    - rds
    - des
    - dts

  gateway:
    image: depscloud/gateway:latest
    hostname: gateway
    depends_on:
    - rds
    - des
    - dts
    ports:
    - 8080:8080
