version: "3.7"

services:
  dts:
    image: depscloud/dts:latest
    hostname: dts

  rds:
    image: depscloud/rds:latest
    hostname: rds
    volumes:
    - ./rds.yaml:/etc/rds/config.yaml
    command:
    - --config=/etc/rds/config.yaml

  des:
    image: depscloud/des:latest
    hostname: des
    
  dis:
    image: depscloud/dis:latest
    hostname: dis
    depends_on:
    - rds
    - des
    - dts
    command:
    - --cron
    - --workers=1

  gateway:
    image: depscloud/gateway:latest
    hostname: gateway
    depends_on:
    - rds
    - des
    - dts
    ports:
    - 8080:8080
