apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depscloud-system
  name: extractor
  labels:
    app: depscloud
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      containers:
      - name: extractor
        image: depscloud/extractor:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

---
# Headless service for stable DNS entries of members
apiVersion: v1
kind: Service
metadata:
  namespace: depscloud-system
  name: extractor
  labels:
    app: depscloud
spec:
  selector:
    app: extractor
  clusterIP: None
  ports:
  - name: grpc
    port: 8090
    targetPort: 8090
