apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depscloud-system
  name: tracker
  labels:
    app: depscloud
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      initContainers:
      - name: service-precheck
        image: mjpitz/service-precheck:latest
        imagePullPolicy: Always
        args:
        - "mysql"
        - "mysql-read"
      containers:
      - name: tracker
        image: depscloud/tracker:latest
        imagePullPolicy: Always
        args:
        - --storage-driver=mysql
        - --storage-address=user:password@tcp(mysql-0.mysql:3306)/depscloud
        - --storage-readonly-address=user:password@tcp(mysql-read:3306)/depscloud
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

---
# Headless service for stable DNS entries of members
apiVersion: v1
kind: Service
metadata:
  namespace: depscloud-system
  name: tracker
  labels:
    app: depscloud
spec:
  selector:
    app: tracker
  clusterIP: None
  ports:
  - name: grpc
    port: 8090
    targetPort: 8090
