apiVersion: v1
kind: Secret
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
