apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depscloud-system
  name: des
  labels:
    app: depscloud
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: des
  template:
    metadata:
      labels:
        app: des
    spec:
      containers:
      - name: des
        image: depscloud/des:latest
        imagePullPolicy: IfNotPresent

---
# Headless service for stable DNS entries of members
apiVersion: v1
kind: Service
metadata:
  namespace: depscloud-system
  name: des
  labels:
    app: depscloud
spec:
  selector:
    app: des
  clusterIP: None
  ports:
  - name: grpc
    port: 8090
    targetPort: 8090
