apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depscloud-system
  name: dts
  labels:
    app: depscloud
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dts
  template:
    metadata:
      labels:
        app: dts
    spec:
      containers:
      - name: dts
        image: depscloud/dts:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

---
# Headless service for stable DNS entries of members
apiVersion: v1
kind: Service
metadata:
  namespace: depscloud-system
  name: dts
  labels:
    app: depscloud
spec:
  selector:
    app: dts
  clusterIP: None
  ports:
  - name: grpc
    port: 8090
    targetPort: 8090
