apiVersion: v1
kind: ConfigMap
metadata:
  namespace: depscloud-system
  name: rds-config
  labels:
    app: depscloud
data:
  config.yaml: |
    accounts:
    - github:
        strategy: HTTP
        organizations:
        - deps-cloud

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depscloud-system
  name: rds
  labels:
    app: depscloud
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rds
  template:
    metadata:
      labels:
        app: rds
    spec:
      volumes:
      - name: config
        configMap:
          name: rds-config
      containers:
      - name: rds
        image: depscloud/rds:latest
        imagePullPolicy: Always
        args:
        - "--config=/etc/rds/config.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/rds
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

---
# Headless service for stable DNS entries of members
apiVersion: v1
kind: Service
metadata:
  namespace: depscloud-system
  name: rds
  labels:
    app: depscloud
spec:
  selector:
    app: rds
  clusterIP: None
  ports:
  - name: grpc
    port: 8090
    targetPort: 8090
